language: nix

git:
  depth: 1

install:
  - git clone --depth=1 https://github.com/jwiegley/haskell-z3.git -b 4.6.0 z3
  - cd z3

env:
  global:
  matrix:
    - GHCVERSION=ghc822
    # - GHCVERSION=ghc842

matrix:
  allow_failures:
    - GHCVERSION=ghc842
  exclude:

script:
  - nix-build --argstr compiler $GHCVERSION

branches:
  only:
    - 4.6.0
