language: nix

git:
  depth: 1

install:
  - git clone --depth=1 https://github.com/jwiegley/haskell-z3.git -b 4.6.0 z3
  - cd z3

env:
  global:
  matrix:
    - GHCVERSION=ghc822 PROFILING=false
    - GHCVERSION=ghc822 PROFILING=true
    # - GHCVERSION=ghc842 PROFILING=false
    # - GHCVERSION=ghc842 PROFILING=true

matrix:
  allow_failures:
    - GHCVERSION=ghc842 PROFILING=false
    - GHCVERSION=ghc842 PROFILING=true
  exclude:

script:
  - nix-build --argstr compiler $GHCVERSION --arg doProfiling $PROFILING

branches:
  only:
    - 4.6.0
