name:       z3
version:    4.6.0
synopsis:   Bindings for the Z3 Theorem Prover
github:     jwiegley/haskell-z3
author:
  - Iago Abal <mail@iagoabal.eu>
  - David Castro <david.castro.dcp@gmail.com>
  - John Wiegley <johnw@newartisans.com>
maintainer:
  - John Wiegley <johnw@newartisans.com>
  - Iago Abal <mail@iagoabal.eu>
category:   Math, SMT, Theorem Provers, Formal Methods, Bit vectors
copyright:  2012-2018, Iago Abal, David Castro, John Wiegley
license:    BSD3

description: >
  Bindings for the (now open source!) Z3 4./x/ Theorem Prover
  (@<https://github.com/Z3Prover/z3>@).

  * "Z3.Base.C" provides the raw foreign imports from Z3's C API.
  * "Z3.Base" does the marshaling of values between Haskell and C,
    and transparently handles reference counting of Z3 objects for you.
  * "Z3.Monad" provides a convenient monadic wrapper for the common
    usage scenario.

  Examples: @<https://bitbucket.org/iago/z3-haskell/src/tip/examples>@
  Changelog: @<https://bitbucket.org/iago/z3-haskell/src/tip/CHANGES.md>@

  Installation:
  * /Unix-like/: Just be sure to use the standard locations for
    dynamic libraries (\/usr\/lib) and header files (\/usr\/include),
    or else use the --extra-lib-dirs and --extra-include-dirs Cabal flags.

  (Hackage reports a build failure because Z3's library is missing.)

extra-source-files:
  - README.md
  - CHANGES.md
  - HACKING.md

dependencies:
  - base >= 4.9 && < 5

ghc-options:
  - -Wall

flags:
  examples:
    description: Build the examples
    manual: True
    default: False

library:
  source-dirs: src
  build-tools: hsc2hs
  default-extensions:
    - FlexibleContexts
    - FlexibleInstances
    - ForeignFunctionInterface
    - MultiParamTypeClasses
  other-extensions:
    - DeriveDataTypeable
    - EmptyDataDecls
    - GeneralizedNewtypeDeriving
    - PatternGuards
  dependencies:
    - containers
    - mtl > 2.1
  when:
    - condition: "!impl(ghc >= 8.0)"
      dependencies:
        - semigroups == 0.18.*

  # In OS X libz3 is linked statically against libgomp. In Windows Z3 is
  # compiled using MS C++.
  when:
    - condition: os(darwin) || os(linux)
      then:
        extra-libraries: z3
      else:
        extra-libraries: gomp z3

executables:
  examples:
    source-dirs: examples
    main: Examples.hs
    when:
      - condition: flag(examples)
        then:
          buildable: true
          dependencies:
            - z3
            - containers
            - mtl >2.1
        else:
          buildable: false

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    ghc-options: -threaded
    default-extensions:
      - ScopedTypeVariables
    other-modules:
      - Z3.Base.Spec
    dependencies:
      - z3
      - hspec >= 2.1
      - QuickCheck >= 2.5.1
